services:
  registry:
    build:
      context: .
      args:
        APP_NAME: registry
    container_name: "rkv-registry"
    ports:
      - "8010:8010"
    environment:
      PORT: 8010
    restart: unless-stopped

  router:
    build:
      context: .
      args:
        APP_NAME: router
    container_name: "rkv-router"
    environment:
      PORT: 8081
      REGISTRY_URL: registry:8010
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - registry

  member:
    build:
      context: .
      args:
        APP_NAME: shard
    environment:
      PORT: 8080
      REGISTRY_URL: registry:8010
      # no fixed SHARD_ADDR because each replica derives its own
    deploy:
      replicas: 2
    restart: unless-stopped
    depends_on:
      - registry
