services:
  member-1:
    build:
      context: .
      args:
        APP_NAME: shard
    environment:
      - PORT=8080
    restart: unless-stopped

  member-2:
    build:
      context: .
      args:
        APP_NAME: shard
    environment:
      - PORT=8080
    restart: unless-stopped

  router:
    build:
      context: .
      args:
        APP_NAME: router
    container_name: "rkv-router"
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - member-1
      - member-2
    environment:
      - PORT=8081
      - MEMBER_ADDR=member-1:8080,member-2:8080
